/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Decision */
        get: operations["read_decision_api_v1_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactIdentityResponse */
        ArtifactIdentityResponse: {
            /**
             * Artifact Schema Version
             * @constant
             */
            artifact_schema_version: "1.0.0";
            /**
             * Artifact Type
             * @constant
             */
            artifact_type: "GameweekDecision";
            /** Final Manifest Sha256 */
            final_manifest_sha256: string;
            /** Preparation Id */
            preparation_id: string;
            /** Semantic Id */
            semantic_id: string;
            /** Sha256 */
            sha256: string;
        };
        /** DecisionReadResponse */
        DecisionReadResponse: {
            /**
             * Api Version
             * @constant
             */
            api_version: "1.0";
            artifact_identity: components["schemas"]["ArtifactIdentityResponse"];
            payload: components["schemas"]["GameweekDecision"];
            trust: components["schemas"]["TrustResponse"];
        };
        /** GameweekDecision v1 */
        GameweekDecision: {
            /** @constant */
            classification: "read_only_validated_single_gameweek_decision";
            engine: components["schemas"]["GameweekDecision_engine"];
            /** Format: date-time */
            frozen_deadline: string;
            /** Format: date-time */
            generation_timestamp: string | null;
            /** @constant */
            generation_timestamp_semantics: "copied_from_upstream_decision_artifact";
            manager_state: components["schemas"]["GameweekDecision_manager_state"];
            players: components["schemas"]["GameweekDecision_player"][];
            recommended_action: components["schemas"]["GameweekDecision_roll_action"] | components["schemas"]["GameweekDecision_transfer_action"];
            reliability: components["schemas"]["GameweekDecision_reliability"];
            roll: components["schemas"]["GameweekDecision_selection"];
            /** @constant */
            schema_name: "GameweekDecision";
            /** @constant */
            schema_version: "1.0.0";
            season: string;
            source_artifacts: components["schemas"]["GameweekDecision_source_artifact"][];
            target_gameweek: number;
            validation: components["schemas"]["GameweekDecision_validation"];
        };
        GameweekDecision_action_selection: components["schemas"]["GameweekDecision_selection"] & {
            incomplete_projection_ids?: unknown[];
            warnings?: unknown[];
        };
        GameweekDecision_engine: {
            decision_artifact_version: string;
            decision_engine_version: string;
            decision_policy: string;
            decision_policy_version: string;
            model_id: string;
            model_scope: string;
            reliability_version: string;
        };
        GameweekDecision_manager_state: {
            bank_units: number;
            /** @enum {unknown} */
            chip_state: "NONE_MODELED";
            current_transfer_cost_points: number;
            entry_id: number;
            free_transfers: number;
            squad: number[];
            verified_provenance: {
                /** @constant */
                authentication_data_exposed: false;
                /** @constant */
                manager_specific_selling_prices: true;
                manager_state_source: string;
                selling_price_source: string;
            };
        };
        GameweekDecision_material_reliability: {
            element_id: number;
            low_sample: boolean;
            prediction_complete: boolean;
            prior_appearances: number;
            prior_starts: number | null;
            prior_total_minutes: number | null;
            prior_xa_per_90: number | null;
            prior_xg_per_90: number | null;
            roles: string[];
            unusually_extreme_attacking_rate: boolean;
            xa_position_population: number;
            xa_position_rank: number | null;
            xg_position_population: number;
            xg_position_rank: number | null;
        };
        GameweekDecision_objective: {
            base_xi_xfp: number;
            captain_bonus_xfp: number;
            total_xfp: number;
        };
        GameweekDecision_player: {
            element_id: number;
            expected_minutes: number | null;
            name: string;
            /** @enum {unknown} */
            position: "GK" | "DEF" | "MID" | "FWD";
            prediction_complete: boolean;
            projected_xfp: number | null;
            /** @enum {unknown} */
            projection_state: "valid_projection" | "verified_blank" | "incomplete_projection" | "missing_projection";
            purchase_price_units: number;
            selling_price_units: number | null;
            team_id: number;
            team_name: string;
            team_short_name: string;
        };
        GameweekDecision_player_transfer_in: {
            element_id: number;
            name: string;
            purchase_price_units: number;
        };
        GameweekDecision_player_transfer_out: {
            element_id: number;
            name: string;
            selling_price_units: number;
        };
        GameweekDecision_reliability: {
            captaincy_materially_changes_gain: boolean;
            changed_action_count: number;
            /** @constant */
            diagnostic_only: true;
            material_players: components["schemas"]["GameweekDecision_material_reliability"][];
            /** @constant */
            official_recommendation_unchanged: true;
            same_exact_action_count: number;
            sensitivity_results: components["schemas"]["GameweekDecision_sensitivity_result"][];
            sensitivity_view_count: number;
            warnings: components["schemas"]["GameweekDecision_warning"][];
        };
        GameweekDecision_roll_action: {
            /** @constant */
            action_type: "ROLL";
            /** @constant */
            objective_gain_vs_roll_xfp: 0;
            selection: components["schemas"]["GameweekDecision_selection"];
        };
        GameweekDecision_selection: {
            bench: number[];
            bench_order_semantics: string;
            captain: number;
            formation: string;
            incomplete_projection_ids: number[];
            objective: components["schemas"]["GameweekDecision_objective"];
            squad: number[];
            starting_xi: number[];
            vice_captain: number;
            warnings: string[];
        };
        GameweekDecision_sensitivity_result: {
            /** @enum {unknown} */
            action_type: "ROLL" | "TRANSFER";
            category: string;
            gain_vs_roll_xfp: number;
            incoming_element_id: number | null;
            objective_xfp: number;
            outgoing_element_id: number | null;
            retains_official_exact_action: boolean;
            view_id: string;
        };
        GameweekDecision_source_artifact: {
            artifact_name: string;
            /** @constant */
            hash_validated: true;
            role: string;
            sha256: string;
        };
        GameweekDecision_transfer_action: {
            /** @constant */
            action_type: "TRANSFER";
            incoming: components["schemas"]["GameweekDecision_player_transfer_in"];
            objective_gain_vs_roll_xfp: number;
            outgoing: components["schemas"]["GameweekDecision_player_transfer_out"];
            resulting_bank_units: number;
            selection: components["schemas"]["GameweekDecision_selection"];
            transfer_cost_points: number;
        };
        GameweekDecision_transfer_validation: {
            applicable: boolean;
            candidate_count: number;
            /** @constant */
            passed: true;
            proof: string;
        };
        GameweekDecision_validation: {
            /** @constant */
            all_source_hashes_validated: true;
            /** @constant */
            bench_accounting_passed: true;
            /** @constant */
            captain_vice_constraints_passed: true;
            /** @constant */
            reliability_provenance_validated: true;
            /** @constant */
            squad_legality_passed: true;
            transfer_legality: components["schemas"]["GameweekDecision_transfer_validation"];
            /** @constant */
            xi_legality_passed: true;
        };
        GameweekDecision_warning: {
            code: string;
            message: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Api Version
             * @constant
             */
            api_version: "1.0";
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** ProblemResponse */
        ProblemResponse: {
            code: components["schemas"]["ReadFailureCode"];
            /** Detail */
            detail: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * ReadFailureCode
         * @enum {string}
         */
        ReadFailureCode: "UNAUTHORIZED" | "NOT_FOUND" | "ARTIFACT_INVALID" | "HASH_MISMATCH" | "UNSUPPORTED_SCHEMA" | "TRUST_CHAIN_INVALID" | "UPSTREAM_UNAVAILABLE";
        /** TrustResponse */
        TrustResponse: {
            /**
             * Complete Chain Validated
             * @constant
             */
            complete_chain_validated: true;
            /** Reader Version */
            reader_version: string;
            /**
             * State
             * @constant
             */
            state: "VERIFIED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ArtifactIdentityResponse = components['schemas']['ArtifactIdentityResponse'];
export type DecisionReadResponse = components['schemas']['DecisionReadResponse'];
export type GameweekDecision = components['schemas']['GameweekDecision'];
export type GameweekDecisionActionSelection = components['schemas']['GameweekDecision_action_selection'];
export type GameweekDecisionEngine = components['schemas']['GameweekDecision_engine'];
export type GameweekDecisionManagerState = components['schemas']['GameweekDecision_manager_state'];
export type GameweekDecisionMaterialReliability = components['schemas']['GameweekDecision_material_reliability'];
export type GameweekDecisionObjective = components['schemas']['GameweekDecision_objective'];
export type GameweekDecisionPlayer = components['schemas']['GameweekDecision_player'];
export type GameweekDecisionPlayerTransferIn = components['schemas']['GameweekDecision_player_transfer_in'];
export type GameweekDecisionPlayerTransferOut = components['schemas']['GameweekDecision_player_transfer_out'];
export type GameweekDecisionReliability = components['schemas']['GameweekDecision_reliability'];
export type GameweekDecisionRollAction = components['schemas']['GameweekDecision_roll_action'];
export type GameweekDecisionSelection = components['schemas']['GameweekDecision_selection'];
export type GameweekDecisionSensitivityResult = components['schemas']['GameweekDecision_sensitivity_result'];
export type GameweekDecisionSourceArtifact = components['schemas']['GameweekDecision_source_artifact'];
export type GameweekDecisionTransferAction = components['schemas']['GameweekDecision_transfer_action'];
export type GameweekDecisionTransferValidation = components['schemas']['GameweekDecision_transfer_validation'];
export type GameweekDecisionValidation = components['schemas']['GameweekDecision_validation'];
export type GameweekDecisionWarning = components['schemas']['GameweekDecision_warning'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type ProblemResponse = components['schemas']['ProblemResponse'];
export type ReadFailureCode = components['schemas']['ReadFailureCode'];
export type TrustResponse = components['schemas']['TrustResponse'];
export type $defs = Record<string, never>;
export interface operations {
    read_decision_api_v1_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionReadResponse"];
                };
            };
            /** @description Fail-closed read error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Fail-closed read error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Fail-closed read error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Fail-closed read error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Fail-closed read error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
