"""Research-only models with no production decision authority."""

from .task033c1 import (
    ARTIFACT_CONTRACT_VERSION,
    COMBINED_IDENTITY,
    PROTOCOL_IDENTITY,
    UA1_IDENTITY,
    UM1_IDENTITY,
    ArtifactHeader,
    Availability,
    HistoryFixture,
    ModeledComponents,
    PeerHistory,
    ResearchContractError,
    ResearchInputError,
    TargetContext,
    U0FixtureInput,
    assemble_combined,
    assemble_ua1_only,
    assemble_um1_only,
    assert_u0_parity,
    build_ua1,
    build_um1,
    build_u0,
    canonical_json_bytes,
)

__all__ = [
    "ARTIFACT_CONTRACT_VERSION",
    "COMBINED_IDENTITY",
    "PROTOCOL_IDENTITY",
    "UA1_IDENTITY",
    "UM1_IDENTITY",
    "ArtifactHeader",
    "Availability",
    "HistoryFixture",
    "ModeledComponents",
    "PeerHistory",
    "ResearchContractError",
    "ResearchInputError",
    "TargetContext",
    "U0FixtureInput",
    "assemble_combined",
    "assemble_ua1_only",
    "assemble_um1_only",
    "assert_u0_parity",
    "build_ua1",
    "build_um1",
    "build_u0",
    "canonical_json_bytes",
]
